from .patterns_con import (
    COMPLEXITY_SETTINGS,
)
from .folder_img_con import SUPPORTED_EXTENSIONS
from .placement_con import (
    MIN_COUNT,
    MAX_COUNT,
    MIN_SCALE,
    MAX_SCALE,
    MIN_ROTATION,
    MAX_ROTATION,
    MAX_DIMENSION_RATIO,
    ATTEMPTS_MULTIPLIER,
)
from .docx_con import _COORD_SIZE, _DEFAULT_PAGE_WIDTH_PT, _DEFAULT_PAGE_HEIGHT_PT

__all__ = [
    "COMPLEXITY_SETTINGS",
    "SUPPORTED_EXTENSIONS",
    "MIN_COUNT",
    "MAX_COUNT",
    "MIN_SCALE",
    "MAX_SCALE",
    "MIN_ROTATION",
    "MAX_ROTATION",
    "MAX_DIMENSION_RATIO",
    "ATTEMPTS_MULTIPLIER",
    "_COORD_SIZE",
    "_DEFAULT_PAGE_WIDTH_PT",
    "_DEFAULT_PAGE_HEIGHT_PT",
]